apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker-service
          image: sentinel/worker-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SENTINEL_API_BASE_URL
              value: "http://api-service.sentinel.svc.cluster.local:8080"
            - name: DB_HOST
              value: "sentinel-postgres.sentinel.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "sentinel"
            - name: DB_USER
              value: "sentinel"
            - name: DB_PASSWORD
              value: "sentinel"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20