apiVersion: v1
kind: Secret
metadata:
  name: sentinel-postgres-secret
  namespace: sentinel
type: Opaque
stringData:
  POSTGRES_DB: sentinel
  POSTGRES_USER: sentinel
  POSTGRES_PASSWORD: sentinelpass